**TALLER 8**

Ingresar al link:

https://scikit-learn.org/stable/datasets/index.html#datasets

Revisar los Datasets: 
-	Boston (Regresión)
-	Diabetes (Regresión)
-	Wine (Clasificación)
-	Breast_cancer (Clasificación)

Escoger un Dataset de regresión y uno de clasificación y crear un modelo de ML para cada uno:

-	Realizar un análisis descriptivo de cada dataset (EDA: Exploratory Data Analysis) esto es resúmenes numéricos de variables que consideren importantes y elaboración de algunos gráficos relevantes.
-	Un modelo de regresión
-	Un modelo de clasificación
-	En el desarrollo de la actividad se debe evidenciar el uso de estadísticos y graficas que evidencie el entendimiento de los datos.  

Se debe detallar todos los pasos que utilizo para la elaboración de los algoritmos

Debe existir una interpretación para cada caso de los resultados en el contexto del dataset elegido

En el desarrollo de la actividad se debe evidenciar el uso de estadísticos y graficas que evidencie el entendimiento de los datos.  





# 1 Conectarse al drive

In [40]:
from google.colab import drive
import os
drive.mount('/content/gdrive')

Drive already mounted at /content/gdrive; to attempt to forcibly remount, call drive.mount("/content/gdrive", force_remount=True).


In [41]:
%cd '/content/gdrive/MyDrive/Python/Taller 8/'

/content/gdrive/MyDrive/Python/Taller 8


# 1.1 Cargar paquetes

In [79]:
import pandas                  as pd
from   scipy import stats
import numpy                   as np
import matplotlib.pyplot       as plt
import seaborn                 as sns
import statsmodels.formula.api as sm
from sklearn import metrics
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LinearRegression
from sklearn.model_selection import train_test_split

# 2 Cargar los datos (Regresión)

In [44]:
data_wine = pd.read_csv('wine_1.csv',sep=',')
data_wine.head()

Wine  Alcohol  Malic.acid   Ash  ...  Color.int   Hue    OD  Proline
0     1    14.23        1.71  2.43  ...       5.64  1.04  3.92     1065
1     1    13.20        1.78  2.14  ...       4.38  1.05  3.40     1050
2     1    13.16        2.36  2.67  ...       5.68  1.03  3.17     1185
3     1    14.37        1.95  2.50  ...       7.80  0.86  3.45     1480
4     1    13.24        2.59  2.87  ...       4.32  1.04  2.93      735

[5 rows x 14 columns]

In [45]:
data_wine.describe()

Wine     Alcohol  Malic.acid  ...         Hue          OD      Proline
count  178.000000  178.000000  178.000000  ...  178.000000  178.000000   178.000000
mean     1.938202   13.000618    2.336348  ...    0.957449    2.611685   746.893258
std      0.775035    0.811827    1.117146  ...    0.228572    0.709990   314.907474
min      1.000000   11.030000    0.740000  ...    0.480000    1.270000   278.000000
25%      1.000000   12.362500    1.602500  ...    0.782500    1.937500   500.500000
50%      2.000000   13.050000    1.865000  ...    0.965000    2.780000   673.500000
75%      3.000000   13.677500    3.082500  ...    1.120000    3.170000   985.000000
max      3.000000   14.830000    5.800000  ...    1.710000    4.000000  1680.000000

[8 rows x 14 columns]

In [46]:
data_wine.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 178 entries, 0 to 177
Data columns (total 14 columns):
 #   Column                Non-Null Count  Dtype  
---  ------                --------------  -----  
 0   Wine                  178 non-null    int64  
 1   Alcohol               178 non-null    float64
 2   Malic.acid            178 non-null    float64
 3   Ash                   178 non-null    float64
 4   Acl                   178 non-null    float64
 5   Mg                    178 non-null    int64  
 6   Phenols               178 non-null    float64
 7   Flavanoids            178 non-null    float64
 8   Nonflavanoid.phenols  178 non-null    float64
 9   Proanth               178 non-null    float64
 10  Color.int             178 non-null    float64
 11  Hue                   178 non-null    float64
 12  OD                    178 non-null    float64
 13  Proline               178 non-null    int64  
dtypes: float64(11), int64(3)
memory usage: 19.6 KB


In [47]:
data_wine.shape

(178, 14)

Notación del dataset wine_1.csv

1) Alcohol

2) Malic acid

3) Ash

4) Alcalinity of ash

5) Magnesium

6) Total phenols

7) Flavanoids

8) Nonflavanoid phenols

9) Proanthocyanins

10)Color intensity

11)Hue

12)OD280/OD315 of diluted wines

13)Proline

# 3 Definir la matriz de diseño (X) y el vector respuesta (y)

In [48]:
x = data_wine.iloc[:,:-1].values # Tomar todas las columnas excepto la ultima
y = data_wine.iloc[:,-1].values # Tomar el vector respuesta (ultima columna)

In [49]:
print(x.shape)
print(y.shape)

(178, 13)
(178,)


# 4 Normalizar usando Standard Scaler
z=(x−μ)/σ 

Haciendo esto las variables deben quedar en un rango entre -2 y 2

In [52]:
x_n = StandardScaler().fit_transform(x)
x_n

array([[-1.21394365,  1.51861254, -0.5622498 , ...,  0.25171685,
         0.36217728,  1.84791957],
       [-1.21394365,  0.24628963, -0.49941338, ..., -0.29332133,
         0.40605066,  1.1134493 ],
       [-1.21394365,  0.19687903,  0.02123125, ...,  0.26901965,
         0.31830389,  0.78858745],
       ...,
       [ 1.37386437,  0.33275817,  1.74474449, ...,  2.22423597,
        -1.61212515, -1.48544548],
       [ 1.37386437,  0.20923168,  0.22769377, ...,  1.83492299,
        -1.56825176, -1.40069891],
       [ 1.37386437,  1.39508604,  1.58316512, ...,  1.79166599,
        -1.52437837, -1.42894777]])

In [53]:
y_1 = np.transpose(np.array([y])) # Llevar a un vector vertical porque estaba como un vector horizontal
y_1.shape

(178, 1)

In [54]:
y_n = StandardScaler().fit_transform(y_1) # Estandarizacion al vector y
y_n

array([[ 1.01300893],
       [ 0.96524152],
       [ 1.39514818],
       [ 2.33457383],
       [-0.03787401],
       [ 2.23903902],
       [ 1.72952002],
       [ 1.74544249],
       [ 0.94931905],
       [ 0.94931905],
       [ 2.43010864],
       [ 1.69767508],
       [ 1.82505483],
       [ 1.28369089],
       [ 2.54793491],
       [ 1.79320989],
       [ 1.69767508],
       [ 1.22000102],
       [ 2.97147258],
       [ 0.3124203 ],
       [ 0.10542821],
       [ 0.07358327],
       [ 0.91747411],
       [ 0.85378424],
       [ 0.3124203 ],
       [ 0.2646529 ],
       [ 1.42699311],
       [ 1.71359755],
       [ 0.53533487],
       [ 0.91747411],
       [ 1.71359755],
       [ 2.44603111],
       [ 0.7741719 ],
       [ 1.55437286],
       [ 1.10854374],
       [ 0.55125733],
       [ 0.42387759],
       [ 1.14038868],
       [ 0.86970671],
       [ 0.04173834],
       [ 0.15319562],
       [ 0.91747411],
       [ 1.10854374],
       [-0.21302116],
       [ 0.43980005],
       [ 1

In [56]:
print('Shape de X',x_n.shape)
print('Shape de y',y_n.shape)

Shape de X (178, 13)
Shape de y (178, 1)


# 5 Definir muestras de entrenamiento y test

In [59]:
x_train, x_test, y_train, y_test = train_test_split(x_n, y_n, test_size=0.25, random_state=42,shuffle=True)

In [60]:
print('Train')
print(x_train.shape)
print(y_train.shape)
print('-------------')
print('Test')
print(x_test.shape)
print(y_test.shape)

Train
(133, 13)
(133, 1)
-------------
Test
(45, 13)
(45, 1)


# 6 Entrenar el modelo

In [61]:
regressor = LinearRegression()
regressor.fit(x_train, y_train)

LinearRegression(copy_X=True, fit_intercept=True, n_jobs=None, normalize=False)

# 7 Analizar los coeficientes

In [62]:
#Recuperamos la intersección
print(regressor.intercept_)

[-0.00232517]


In [63]:
print(regressor.coef_)

[[-0.75990723  0.15293898 -0.07397694  0.12222498 -0.08544996  0.08093001
   0.1573841  -0.42133872 -0.04912347  0.07940309  0.36741515  0.03440944
  -0.07374578]]


In [64]:
regressor.coef_[0]

array([-0.75990723,  0.15293898, -0.07397694,  0.12222498, -0.08544996,
        0.08093001,  0.1573841 , -0.42133872, -0.04912347,  0.07940309,
        0.36741515,  0.03440944, -0.07374578])

In [74]:
data_wine_x = data_wine.drop(columns=['Proline'])
data_wine_x.columns

Index(['Wine', 'Alcohol', 'Malic.acid', 'Ash', 'Acl', 'Mg', 'Phenols',
       'Flavanoids', 'Nonflavanoid.phenols', 'Proanth', 'Color.int', 'Hue',
       'OD'],
      dtype='object')

# 8 Calcular los vectores de media y desviacion estandar

In [75]:
np.mean(data_wine_x,axis=0)

Wine                     1.938202
Alcohol                 13.000618
Malic.acid               2.336348
Ash                      2.366517
Acl                     19.494944
Mg                      99.741573
Phenols                  2.295112
Flavanoids               2.029270
Nonflavanoid.phenols     0.361854
Proanth                  1.590899
Color.int                5.058090
Hue                      0.957449
OD                       2.611685
dtype: float64

In [76]:
np.std(data_wine_x,axis=0)

Wine                     0.772855
Alcohol                  0.809543
Malic.acid               1.114004
Ash                      0.273572
Acl                      3.330170
Mg                      14.242308
Phenols                  0.624091
Flavanoids               0.996049
Nonflavanoid.phenols     0.124103
Proanth                  0.570749
Color.int                2.311765
Hue                      0.227929
OD                       0.707993
dtype: float64

In [77]:
df=pd.DataFrame(regressor.coef_[0], data_wine_x.columns, columns=['Coeficiente'])
df['Medias']=np.mean(data_wine_x,axis=0)
df['Desviacion']=np.std(data_wine_x,axis=0)
df['Coef_final']=df.Medias + (df.Coeficiente*df.Desviacion) # Calculo del coeficiente sin normalizar
df

Coeficiente     Medias  Desviacion  Coef_final
Wine                    -0.759907   1.938202    0.772855    1.350904
Alcohol                  0.152939  13.000618    0.809543   13.124429
Malic.acid              -0.073977   2.336348    1.114004    2.253938
Ash                      0.122225   2.366517    0.273572    2.399954
Acl                     -0.085450  19.494944    3.330170   19.210381
Mg                       0.080930  99.741573   14.242308  100.894203
Phenols                  0.157384   2.295112    0.624091    2.393334
Flavanoids              -0.421339   2.029270    0.996049    1.609596
Nonflavanoid.phenols    -0.049123   0.361854    0.124103    0.355758
Proanth                  0.079403   1.590899    0.570749    1.636218
Color.int                0.367415   5.058090    2.311765    5.907467
Hue                      0.034409   0.957449    0.227929    0.965292
OD                      -0.073746   2.611685    0.707993    2.559474

# 9 Calcular las predicciones

In [78]:
#Hacemos nuestras predicciones
y_pred = regressor.predict(x_test)
y_pred

array([[ 0.97271604],
       [ 0.94287671],
       [-0.79876967],
       [ 1.11901564],
       [-0.63108268],
       [ 1.37068057],
       [-1.07261686],
       [-0.31064961],
       [-0.71783598],
       [-0.72699756],
       [ 0.63383671],
       [-0.2528659 ],
       [ 0.36343669],
       [-0.59656526],
       [ 1.50225674],
       [-0.91431455],
       [-0.55395307],
       [-0.67027437],
       [ 1.22930137],
       [-0.83556849],
       [ 1.47055375],
       [-0.434413  ],
       [-0.12635708],
       [-0.05434212],
       [-0.1616749 ],
       [-0.06439405],
       [-0.8196852 ],
       [-0.16658075],
       [-0.68067731],
       [ 1.35742301],
       [ 1.06519622],
       [-1.02386761],
       [-0.98795887],
       [ 1.1596794 ],
       [ 1.06193423],
       [ 0.97131572],
       [ 1.0390693 ],
       [-1.01752314],
       [-0.671921  ],
       [ 0.6688603 ],
       [ 0.54171368],
       [-0.72621746],
       [-0.44126773],
       [ 0.12387613],
       [-0.89712194]])

In [80]:
print('Mean Absolute Error:', metrics.mean_absolute_error(y_test, y_pred))
print('Mean Squared Error:', metrics.mean_squared_error(y_test, y_pred))
print('Root Mean Squared Error:', np.sqrt(metrics.mean_squared_error(y_test, y_pred)))

Mean Absolute Error: 0.4740948075813741
Mean Squared Error: 0.34272344148046824
Root Mean Squared Error: 0.5854258633511746


In [103]:
media_y = np.mean(data_wine_x.columns)
desviacion_y= np.mean(data_wine_x.columns)
desviacion_y

TypeError: ignored

In [102]:
df_n= pd.DataFrame(X_test, columns=data_boston_x.columns)
df_n['y_pred']=y_pred
df_n['y_pred_final']=(y_pred*desviacion_y)+media_y

NameError: ignored